name: glift_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase: ^2.10.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  fl_chart: ^1.1.1
  intl: ^0.20.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.1
  flutter_ringtone_player: ^3.2.0
  vibration: ^1.8.4
  shared_preferences: ^2.5.4
  custom_refresh_indicator: ^4.0.1
  audioplayers: ^6.5.1
  flutter_quill: ^11.5.0
  flutter_quill_delta_from_html: ^1.5.3
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#673ab7"

  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

  linux:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/congrats.gif
    - assets/images/
    - assets/icons/
    - assets/sounds/
